name: fighthub
description: MMA Prediction & Community Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Supabase Integration
  supabase_flutter: ^2.3.4
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Real-time Features
  web_socket_channel: ^2.4.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Utilities
  uuid: ^4.2.1
  logger: ^2.0.2+1
  
  # Social Features
  url_launcher: ^6.2.1
  
  # ML Integration
  tflite_flutter: ^0.10.4
  
  # Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700 
